{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bff9e27",
   "metadata": {},
   "outputs": [],
   "source": [
    "import Labber\n",
    "# connect to server \n",
    "client = Labber.connectToServer('localhost') # get list of instruments \n",
    "#instruments = client.getListOfInstrumentsString() \n",
    "#for instr in instruments: \n",
    "#    print(instr) # close connection \n",
    "\n",
    "# reset all QDevil channels to 0 V\n",
    "QDevil = client.connectToInstrument('QDevil QDAC', dict(interface='Serial', address='3'))\n",
    "for n in range(24):\n",
    "    if n+1 < 10:\n",
    "        QDevil.setValue(\"CH0\" + str(n+1) + \" Voltage\", 0.0)\n",
    "    else:\n",
    "        QDevil.setValue(\"CH\" + str(n+1) + \" Voltage\", 0.0)\n",
    "# setting CH06 to sweet spot\n",
    "DC_ss = 6.4352E-3\n",
    "QDevil.setValue(\"CH06 Voltage\", DC_ss)\n",
    "\n",
    "# digital attenuators\n",
    "Vaunix1 = client.connectToInstrument('Painter Vaunix Lab Brick Digital Attenuator', dict(interface='USB', address='25606'))\n",
    "Vaunix2 = client.connectToInstrument('Painter Vaunix Lab Brick Digital Attenuator', dict(interface='USB', address='25607'))\n",
    "ROI = 38\n",
    "ROO = 10\n",
    "Vaunix1.setValue(\"Attenuation\", ROI)\n",
    "Vaunix2.setValue(\"Attenuation\", ROO)\n",
    "\n",
    "# TWPA pump\n",
    "SG = client.connectToInstrument('Rohde&Schwarz RF Source', dict(interface='TCPIP', address='192.168.88.2'))\n",
    "freq_TWPA = 6730.6E6\n",
    "pwr_TWPA = -11.3\n",
    "SG.setValue('Frequency', freq_TWPA)\n",
    "SG.setValue('Power', pwr_TWPA)\n",
    "\n",
    "client.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23d55569",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(datetime.datetime.now(),1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e498e91-3cad-4bf1-936e-f06c6ed7cba4",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "from qm.qua import *\n",
    "from qm.QuantumMachinesManager import QuantumMachinesManager\n",
    "from qm import SimulationConfig, LoopbackInterface\n",
    "from configuration import *\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from scipy import signal\n",
    "from qualang_tools.loops import from_array\n",
    "import qdac\n",
    "import random\n",
    "import math\n",
    "import time\n",
    "%matplotlib qt\n",
    "\n",
    "# Start to save data\n",
    "import datetime \n",
    "import os\n",
    "import pandas as pd \n",
    "\n",
    "now = datetime.datetime.now()\n",
    "year = now.strftime(\"%Y\")\n",
    "month = now.strftime(\"%m\")\n",
    "day = now.strftime(\"%d\")\n",
    "hour = now.strftime(\"%H\")\n",
    "minute = now.strftime(\"%M\")\n",
    "second  = now.strftime(\"%S\")\n",
    "\n",
    "tPath = os.path.join(r'Z:\\LabberData_DF5\\QM_Data_DF5',year,month,'Data_'+month+day)\n",
    "if not os.path.exists(tPath):\n",
    "   os.makedirs(tPath)\n",
    "exp_name = 'RR_spec_wFlux'\n",
    "qubit_name = 'Q2'\n",
    "\n",
    "f_str =exp_name + '_'+ qubit_name +'_'+ hour+ '_' + minute +'_' + second\n",
    "f_name= f_str+'.csv'\n",
    "j_name = f_str + '_state.json'\n",
    "p_name= f_str+'.png'\n",
    "\n",
    "# End to save data\n",
    "\n",
    "\n",
    "#########################################\n",
    "# Set-up the machine and get the config #\n",
    "#########################################\n",
    "\n",
    "print(datetime.datetime.now(),1)\n",
    "machine = QuAM(\"quam_state.json\")\n",
    "#machine.resonators[0].f_readout+=1.68e6\n",
    "# machine.resonators[0].readout_pulse_amp=0.27\n",
    "config = build_config(machine)\n",
    "print(datetime.datetime.now(),2)\n",
    "##############################\n",
    "# Program-specific variables #\n",
    "##############################\n",
    "\n",
    "n_avg = 1000  # Number of averaging loops\n",
    "\n",
    "cooldown_time = 50  # Resonator cooldown time \n",
    "flux_settle_time = 250  # Flux settle time \n",
    "\n",
    "flux_pts = 250\n",
    "\n",
    "#dcs = np.linspace(-0.49, 0.49, flux_pts)\n",
    "dcs = np.arange(-9,9.5,0.5)\n",
    "dfs = np.arange(-14.62e6, 15.40e6, 0.2e6)\n",
    "number_of_qubits = 1\n",
    "resonators_list = [i for i in range(number_of_qubits)]\n",
    "res_if_list = [machine.resonators[i].f_readout - machine.resonators[i].lo for i in range(number_of_qubits)]\n",
    "\n",
    "qubit_index = 0\n",
    "\n",
    "print(datetime.datetime.now(),3)\n",
    "for idx_dc, _ in enumerate(dcs):\n",
    "    dc = dcs[idx_dc]\n",
    "    QDevil.setValue(\"CH06 Voltage\", dc)\n",
    "    print(datetime.datetime.now(),4)\n",
    "###################\n",
    "# The QUA program #\n",
    "###################\n",
    "    time.sleep(0.5)\n",
    "\n",
    "    with program() as resonator_spec_2D:\n",
    "        n = declare(int)  # Averaging index\n",
    "        df = declare(int)  # Resonator frequency\n",
    "        # dc = declare(fixed)  # flux dc level|\n",
    "        I = declare(fixed)\n",
    "        Q = declare(fixed)\n",
    "        I_st = declare_stream()\n",
    "        Q_st = declare_stream()\n",
    "        n_st = declare_stream()\n",
    "        #wait(flux_settle_time , machine.resonators[qubit_index].name, machine.qubits[qubit_index].name)\n",
    "\n",
    "        with for_(n, 0, n < n_avg, n + 1):\n",
    "            with for_(*from_array(df, dfs)):\n",
    "                # Update the resonator frequency\n",
    "                update_frequency(machine.resonators[qubit_index].name, df + res_if_list[qubit_index])\n",
    "                # with for_(*from_array(dc, dcs)):\n",
    "                    # Flux sweeping\n",
    "                    # set_dc_offset(machine.flux_lines[qubit_index].name, \"single\", dc)\n",
    "                    # wait(flux_settle_time * u.ns, machine.resonators[qubit_index].name, machine.qubits[qubit_index].name)\n",
    "                    # Measure the resonator\n",
    "                measure(\n",
    "                    \"readout\",\n",
    "                    machine.resonators[qubit_index].name,\n",
    "                    None,\n",
    "                    dual_demod.full(\"cos\", \"out1\", \"sin\", \"out2\", I),\n",
    "                    dual_demod.full(\"minus_sin\", \"out1\", \"cos\", \"out2\", Q),\n",
    "                )\n",
    "                # Wait for the resonator to cooldown\n",
    "                wait(cooldown_time * u.us - machine.resonators[0].readout_pulse_length * u.ns - 240 * u.ns, machine.resonators[qubit_index].name)\n",
    "                # Save data to the stream processing\n",
    "                save(I, I_st)\n",
    "                save(Q, Q_st)\n",
    "            save(n, n_st)\n",
    "\n",
    "        with stream_processing():\n",
    "            # I_st.buffer(len(dcs)).buffer(len(dfs)).average().save(\"I\")\n",
    "            # Q_st.buffer(len(dcs)).buffer(len(dfs)).average().save(\"Q\")\n",
    "            I_st.buffer(len(dfs)).average().save(\"I\")\n",
    "            Q_st.buffer(len(dfs)).average().save(\"Q\")\n",
    "            n_st.save(\"iteration\")\n",
    "\n",
    "\n",
    "    #####################################\n",
    "    #  Open Communication with the QOP  #\n",
    "    #####################################\n",
    "    print(datetime.datetime.now(),5)\n",
    "    qmm = QuantumMachinesManager(machine.network.qop_ip, cluster_name=machine.network.cluster_name, octave=octave_config)\n",
    "    print(datetime.datetime.now(),6)\n",
    "    simulation = False\n",
    "\n",
    "    if simulation:\n",
    "        simulation_config = SimulationConfig(\n",
    "        duration=100_000, simulation_interface=LoopbackInterface([(\"con1\", 3, \"con1\", 1)]))\n",
    "        job = qmm.simulate(config, resonator_spec_2D, simulation_config)\n",
    "        job.get_simulated_samples().con1.plot()\n",
    "\n",
    "    else:\n",
    "        qm = qmm.open_qm(config)\n",
    "        job = qm.execute(resonator_spec_2D)\n",
    "        # Get results from QUA program\n",
    "        results = fetching_tool(job, data_list=[\"I\", \"Q\", \"iteration\"], mode=\"live\")\n",
    "        print(datetime.datetime.now(),7)\n",
    "        fig = plt.figure(1)\n",
    "        plt.rcParams['figure.figsize'] = [12, 8]\n",
    "        interrupt_on_close(fig, job)  #  Interrupts the job when closing the figure\n",
    "\n",
    "        # Progress bar\n",
    "        progress_counter(idx_dc, len(dcs))\n",
    "\n",
    "        while results.is_processing():\n",
    "            I_tmp, Q_tmp, iteration_tmp = results.fetch_all()\n",
    "            I_tmp = u.demod2volts(I_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "            Q_tmp = u.demod2volts(Q_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "\n",
    "            # Live plotting\n",
    "            plt.subplot(211)\n",
    "            plt.cla()\n",
    "            plt.title(\"Resonator spectroscopy amplitude\")\n",
    "            plt.plot((dfs ) / u.MHz, np.sqrt(I_tmp**2 + Q_tmp**2), \".\")\n",
    "            plt.xlabel(\"Frequency [MHz]\")\n",
    "            plt.ylabel(r\"$\\sqrt{I^2 + Q^2}$ [a.u.]\")\n",
    "            plt.subplot(212)\n",
    "            plt.cla()\n",
    "            # detrend removes the linear increase of phase\n",
    "            phase = signal.detrend(np.unwrap(np.angle(I_tmp + 1j * Q_tmp)))\n",
    "            plt.title(\"Resonator spectroscopy phase\")\n",
    "            plt.plot((dfs ) / u.MHz, phase, \".\")\n",
    "            plt.xlabel(\"Frequency [MHz]\")\n",
    "            plt.ylabel(\"Phase [rad]\")\n",
    "            plt.pause(0.1)\n",
    "\n",
    "        if idx_dc == 0:\n",
    "            I_2D = I_tmp\n",
    "            Q_2D = Q_tmp\n",
    "\n",
    "        else:\n",
    "            I_2D = np.hstack([I_2D, I_tmp])\n",
    "            Q_2D = np.hstack([Q_2D, Q_tmp])\n",
    "\n",
    "# I_2D = np.reshape(I_2D, (len(dcs), len(I_tmp)))\n",
    "# Q_2D = np.reshape(Q_2D, (len(dcs), len(Q_tmp)))\n",
    "\n",
    "# 2D plot\n",
    "fig = plt.figure()\n",
    "plt.rcParams['figure.figsize'] = [12, 8]\n",
    "# 2D spectroscopy plot\n",
    "plt.subplot(211)\n",
    "plt.cla()\n",
    "plt.title(\"Resonator spectroscopy tuning curve\")\n",
    "plt.pcolor(dfs/ u.MHz, dcs, np.sqrt(I_2D**2 + Q_2D**2),cmap=\"seismic\")\n",
    "plt.xlabel(\"DC flux level [V]\")\n",
    "plt.ylabel(\"Frequency [MHz]\")\n",
    "plt.colorbar()\n",
    "#plt.axvline(x=0)\n",
    "plt.subplot(212)\n",
    "plt.cla()\n",
    "plt.title(\"Resonator spectroscopy phase\")\n",
    "phase = signal.detrend(np.unwrap(np.angle(I_2D + 1j * Q_2D)))\n",
    "plt.pcolor(dfs/ u.MHz, dcs, phase ,cmap=\"seismic\")\n",
    "plt.xlabel(\"DC flux level [V]\")\n",
    "plt.ylabel(\"Frequency [MHz]\")\n",
    "plt.colorbar()\n",
    "#plt.axvline(x=0)\n",
    "#plt.pause(0.1)\n",
    "plt.tight_layout()\n",
    "print(datetime.datetime.now(),8)\n",
    "plt.savefig(os.path.join(tPath, p_name))\n",
    "print(datetime.datetime.now(),9)    \n",
    "\n",
    "    \n",
    "    \n",
    "#     fig = plt.figure(1)\n",
    "#     plt.rcParams['figure.figsize'] = [12, 8]\n",
    "#     interrupt_on_close(fig, job)  #  Interrupts the job when closing the figure\n",
    "\n",
    "#     # Progress bar\n",
    "#     progress_counter(idx_dc, len(dcs))\n",
    "\n",
    "#     while results.is_processing():\n",
    "#         I_tmp, Q_tmp, iteration_tmp = results.fetch_all()\n",
    "#         I_tmp = u.demod2volts(I_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "#         Q_tmp = u.demod2volts(Q_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "\n",
    "\n",
    "#     #         # Live plotting\n",
    "#     #         plt.subplot(211)\n",
    "#     #         plt.cla()\n",
    "#     #         plt.title(\"Resonator spectroscopy amplitude\")\n",
    "#     #         plt.plot((dfs ) / u.MHz, np.sqrt(I_tmp**2 + Q_tmp**2), \".\")\n",
    "#     #         plt.xlabel(\"Frequency [MHz]\")\n",
    "#     #         plt.ylabel(r\"$\\sqrt{I^2 + Q^2}$ [a.u.]\")\n",
    "#     #         plt.subplot(212)\n",
    "#     #         plt.cla()\n",
    "#     #         # detrend removes the linear increase of phase\n",
    "#     #         phase = signal.detrend(np.unwrap(np.angle(I_tmp + 1j * Q_tmp)))\n",
    "#     #         plt.title(\"Resonator spectroscopy phase\")\n",
    "#     #         plt.plot((dfs ) / u.MHz, phase, \".\")\n",
    "#     #         plt.xlabel(\"Frequency [MHz]\")\n",
    "#     #         plt.ylabel(\"Phase [rad]\")\n",
    "#     #         plt.pause(0.1)\n",
    "\n",
    "#     if idx_dc == 0:\n",
    "#         I_2D = I_tmp\n",
    "#         Q_2D = Q_tmp\n",
    "#     else:\n",
    "#         I_2D = np.hstack([I_2D, I_tmp])\n",
    "#         Q_2D = np.hstack([Q_2D, Q_tmp])\n",
    "\n",
    "# I_2D = np.reshape(I_2D, (len(dcs), len(I_tmp)))\n",
    "# Q_2D = np.reshape(Q_2D, (len(dcs), len(Q_tmp)))\n",
    "# 2D plot\n",
    "# fig = plt.figure()\n",
    "# plt.rcParams['figure.figsize'] = [12, 8]\n",
    "# # 2D spectroscopy plot\n",
    "# plt.subplot(211)\n",
    "# plt.cla()\n",
    "# plt.title(\"Resonator spectroscopy tuning curve\")\n",
    "# plt.pcolor(dfs/ u.MHz, dcs, np.sqrt(I_2D**2 + Q_2D**2),cmap=\"seismic\")\n",
    "# plt.xlabel(\"DC flux level [V]\")\n",
    "# plt.ylabel(\"Frequency [MHz]\")\n",
    "# plt.colorbar()\n",
    "# #plt.axvline(x=0)\n",
    "# plt.subplot(212)\n",
    "# plt.cla()\n",
    "# plt.title(\"Resonator spectroscopy phase\")\n",
    "# phase = signal.detrend(np.unwrap(np.angle(I_2D + 1j * Q_2D)))\n",
    "# plt.pcolor(dfs/ u.MHz, dcs, phase ,cmap=\"seismic\")\n",
    "# plt.xlabel(\"DC flux level [V]\")\n",
    "# plt.ylabel(\"Frequency [MHz]\")\n",
    "# plt.colorbar()\n",
    "# #plt.axvline(x=0)\n",
    "# #plt.pause(0.1)\n",
    "# plt.tight_layout()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2697957f",
   "metadata": {},
   "outputs": [],
   "source": [
    "len(I_2D)/len(dfs)\n",
    "dcs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "66d470fe-c24e-4273-9c1e-72097961fc37",
   "metadata": {},
   "outputs": [],
   "source": [
    "## convert everything to lists so they are easy to parse in Matlab if desired\n",
    "if isinstance(dcs,np.ndarray) == True:\n",
    "   dcs1=dcs.tolist()\n",
    "else:  \n",
    "    pass\n",
    "if isinstance(dfs,np.ndarray) == True:\n",
    "   dfs1=dfs.tolist()\n",
    "else:  \n",
    "    pass\n",
    "if isinstance(I_2D,np.ndarray) == True:\n",
    "   I1=I_2D.tolist()\n",
    "else:  \n",
    "    pass\n",
    "if isinstance(Q_2D,np.ndarray) == True:\n",
    "   Q1=Q_2D.tolist()\n",
    "else:  \n",
    "    pass\n",
    "\n",
    "# fq = np.asarray(dfs)\n",
    "# dc = np.asarray(dcs)\n",
    "# dataI = np.asarray(I)\n",
    "# dataQ = np.asarray(Q)\n",
    "# d1 = pd.DataFrame(fq)\n",
    "# d2 = pd.DataFrame(dc)\n",
    "# d3 = pd.DataFrame(dataI)\n",
    "# d4 = pd.DataFrame(dataQ)\n",
    "# frames = [d1, d2, d3, d4]\n",
    "# result = pd.concat(frames)\n",
    "# # df.index = ['flux', 'freq', 'I', 'Q']\n",
    "# result.to_csv(os.path.join(tPath, f_name),header=False, index=False)\n",
    "# open(os.path.join(tPath, j_name), \"w\").write(open(\"quam_state.json\").read())\n",
    "\n",
    "data = [('Variable', 'Value'), ('Flux', dcs1), ('Freq', dfs1), ('I', I1), ('Q', Q1)]\n",
    "df = pd.DataFrame(data,index=None, columns=None)\n",
    "df.to_csv(os.path.join(tPath, f_name),header=False, index=False)\n",
    "open(os.path.join(tPath, j_name), \"w\").write(open(\"quam_state.json\").read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb183998-f37c-466e-b10b-860ba1f57066",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Fit to a cosine function to optimize readout later\n",
    "\n",
    "from scipy.optimize import curve_fit\n",
    "\n",
    "I = np.array(I)\n",
    "Q = np.array(Q)\n",
    "dfs = np.array(dfs)\n",
    "dcs = np.array(dcs)\n",
    "\n",
    "def cosine_func(x, amplitude, frequency, phase, offset):\n",
    "        return amplitude * np.cos(2 * np.pi * frequency * x + phase) + offset\n",
    "\n",
    "Z = I + 1j*Q\n",
    "mag = np.abs(Z)\n",
    "mag_transpose = mag.T\n",
    "minimas = []\n",
    "for i in range(len(dcs)):\n",
    "    minimas.append(dfs[np.argmin(mag_transpose[i])])\n",
    "minimas = np.array(minimas)\n",
    "initial_guess = [1, 0.5, 0, -1]  # Initial guess for the parameters\n",
    "fit_params, _ = curve_fit(cosine_func, dcs, minimas/1e6, p0=initial_guess)\n",
    "\n",
    "# Get the fitted values\n",
    "amplitude_fit, frequency_fit, phase_fit, offset_fit = fit_params\n",
    "print('Fit parameters:', fit_params)\n",
    "\n",
    "# Generate the fitted curve using the fitted parameters\n",
    "fitted_curve = cosine_func(dcs, amplitude_fit, frequency_fit, phase_fit, offset_fit)\n",
    "plt.figure()\n",
    "plt.xlabel(\"Flux level [V]\")\n",
    "plt.ylabel(\"Frequency [MHz]\")\n",
    "plt.pcolor(dcs,dfs/u.MHz, np.abs(Z))\n",
    "plt.plot(dcs, minimas/u.MHz, '.-', color='red')\n",
    "plt.plot(dcs, fitted_curve, label='Fitted Cosine', color='orange')\n",
    "plt.colorbar()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0cdaafa7-e2f8-48d0-9545-6e93d412c5f0",
   "metadata": {},
   "source": [
    "## fitted in MATLAB to find sweet spot DC flux = 6.4352 mV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aed2a0a2-a3a0-4d83-8c6c-f0fde29e565f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff328db7-da3f-4120-ac44-bafe47620903",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f5fd88d9-54fb-4c1d-a7f9-9fc0bc597106",
   "metadata": {},
   "outputs": [],
   "source": [
    "machine._save(\"quam_state.json\", flat_data=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5160e20-fe70-4333-8972-240fedef181c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import Labber\n",
    "# connect to server \n",
    "client = Labber.connectToServer('localhost') # get list of instruments \n",
    "#instruments = client.getListOfInstrumentsString() \n",
    "#for instr in instruments: \n",
    "#    print(instr) # close connection \n",
    "\n",
    "# reset all QDevil channels to 0 V\n",
    "QDevil = client.connectToInstrument('QDevil QDAC', dict(interface='Serial', address='3'))\n",
    "for n in range(24):\n",
    "    if n+1 < 10:\n",
    "        QDevil.setValue(\"CH0\" + str(n+1) + \" Voltage\", 0.0)\n",
    "    else:\n",
    "        QDevil.setValue(\"CH\" + str(n+1) + \" Voltage\", 0.0)\n",
    "# setting CH06 to sweet spot\n",
    "DC_ss = 6.4352E-3\n",
    "QDevil.setValue(\"CH06 Voltage\", DC_ss)\n",
    "\n",
    "# digital attenuators\n",
    "Vaunix1 = client.connectToInstrument('Painter Vaunix Lab Brick Digital Attenuator', dict(interface='USB', address='25606'))\n",
    "Vaunix2 = client.connectToInstrument('Painter Vaunix Lab Brick Digital Attenuator', dict(interface='USB', address='25607'))\n",
    "ROI = 38\n",
    "ROO = 10\n",
    "Vaunix1.setValue(\"Attenuation\", ROI)\n",
    "Vaunix2.setValue(\"Attenuation\", ROO)\n",
    "\n",
    "# TWPA pump\n",
    "SG = client.connectToInstrument('Rohde&Schwarz RF Source', dict(interface='TCPIP', address='192.168.88.2'))\n",
    "freq_TWPA = 6730.6E6\n",
    "pwr_TWPA = -11.3\n",
    "SG.setValue('Frequency', freq_TWPA)\n",
    "SG.setValue('Power', pwr_TWPA)\n",
    "\n",
    "# client.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d4bbcbe-2e10-43b8-96cc-a2aa4ca37f33",
   "metadata": {},
   "outputs": [],
   "source": [
    "from qm.qua import *\n",
    "from qm.QuantumMachinesManager import QuantumMachinesManager\n",
    "from qm import SimulationConfig, LoopbackInterface\n",
    "from configuration import *\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from scipy import signal\n",
    "from qualang_tools.loops import from_array\n",
    "import qdac\n",
    "import random\n",
    "import math\n",
    "import time\n",
    "import xarray as xr\n",
    "%matplotlib qt\n",
    "\n",
    "# Start to save data\n",
    "import datetime \n",
    "import os\n",
    "import pandas as pd \n",
    "\n",
    "now = datetime.datetime.now()\n",
    "year = now.strftime(\"%Y\")\n",
    "month = now.strftime(\"%m\")\n",
    "day = now.strftime(\"%d\")\n",
    "hour = now.strftime(\"%H\")\n",
    "minute = now.strftime(\"%M\")\n",
    "second  = now.strftime(\"%S\")\n",
    "\n",
    "tPath = os.path.join(r'Z:\\LabberData_DF5\\QM_Data_DF5',year,month,'Data_'+month+day)\n",
    "if not os.path.exists(tPath):\n",
    "   os.makedirs(tPath)\n",
    "exp_name = 'RR_spec_wFlux'\n",
    "qubit_name = 'Q2'\n",
    "\n",
    "f_str =exp_name + '_'+ qubit_name +'_'+ hour+ '_' + minute +'_' + second\n",
    "f_name= f_str+'.csv'\n",
    "j_name = f_str + '_state.json'\n",
    "p_name= f_str+'.png'\n",
    "\n",
    "# End to save data\n",
    "\n",
    "\n",
    "#########################################\n",
    "# Set-up the machine and get the config #\n",
    "#########################################\n",
    "machine = QuAM(\"quam_state.json\")\n",
    "#machine.resonators[0].f_readout+=1.68e6\n",
    "# machine.resonators[0].readout_pulse_amp=0.27\n",
    "config = build_config(machine)\n",
    "\n",
    "##############################\n",
    "# Program-specific variables #\n",
    "##############################\n",
    "\n",
    "n_avg = 500  # Number of averaging loops\n",
    "\n",
    "cooldown_time = 10_000  # Resonator cooldown time \n",
    "flux_settle_time = 250  # Flux settle time \n",
    "\n",
    "flux_pts = 250\n",
    "\n",
    "#dcs = np.linspace(-0.49, 0.49, flux_pts)\n",
    "dcs = np.arange(-9,9,3)\n",
    "dfs = np.arange(-12.5e6, 7.5e6, 0.5e6)\n",
    "\n",
    "number_of_qubits = 1\n",
    "resonators_list = [i for i in range(number_of_qubits)]\n",
    "res_if_list = [machine.resonators[i].f_readout - machine.resonators[i].lo for i in range(number_of_qubits)]\n",
    "\n",
    "qubit_index = 0\n",
    "\n",
    "\n",
    "for idx_dc, _ in enumerate(dcs):\n",
    "    dc = dcs[idx_dc]\n",
    "    QDevil.setValue(\"CH06 Voltage\", dc)\n",
    "\n",
    "###################\n",
    "# The QUA program #\n",
    "###################\n",
    "    time.sleep(1)\n",
    "\n",
    "    with program() as resonator_spec_2D:\n",
    "        n = declare(int)  # Averaging index\n",
    "        df = declare(int)  # Resonator frequency\n",
    "        # dc = declare(fixed)  # flux dc level|\n",
    "        I = declare(fixed)\n",
    "        Q = declare(fixed)\n",
    "        I_st = declare_stream()\n",
    "        Q_st = declare_stream()\n",
    "        n_st = declare_stream()\n",
    "        df_st = declare_stream()\n",
    "        #wait(flux_settle_time , machine.resonators[qubit_index].name, machine.qubits[qubit_index].name)\n",
    "\n",
    "        with for_(n, 0, n < n_avg, n + 1):\n",
    "            with for_(*from_array(df, dfs)):\n",
    "                # Update the resonator frequency\n",
    "                update_frequency(machine.resonators[qubit_index].name, df + res_if_list[qubit_index])\n",
    "                # with for_(*from_array(dc, dcs)):\n",
    "                    # Flux sweeping\n",
    "                    # set_dc_offset(machine.flux_lines[qubit_index].name, \"single\", dc)\n",
    "                    # wait(flux_settle_time * u.ns, machine.resonators[qubit_index].name, machine.qubits[qubit_index].name)\n",
    "                    # Measure the resonator\n",
    "                measure(\n",
    "                    \"readout\",\n",
    "                    machine.resonators[qubit_index].name,\n",
    "                    None,\n",
    "                    dual_demod.full(\"cos\", \"out1\", \"sin\", \"out2\", I),\n",
    "                    dual_demod.full(\"minus_sin\", \"out1\", \"cos\", \"out2\", Q),\n",
    "                )\n",
    "                # Wait for the resonator to cooldown\n",
    "                wait(cooldown_time * u.ns, machine.resonators[qubit_index].name)\n",
    "                # Save data to the stream processing\n",
    "                save(I, I_st)\n",
    "                save(Q, Q_st)\n",
    "                save(df,df_st)\n",
    "            save(n, n_st)\n",
    "\n",
    "        with stream_processing():\n",
    "            # I_st.buffer(len(dcs)).buffer(len(dfs)).average().save(\"I\")\n",
    "            # Q_st.buffer(len(dcs)).buffer(len(dfs)).average().save(\"Q\")\n",
    "            I_st.buffer(len(dfs)).average().save(\"I\")\n",
    "            Q_st.buffer(len(dfs)).average().save(\"Q\")\n",
    "            n_st.save(\"iteration\")\n",
    "            df_st.buffer(len(dfs)).save(\"df\")\n",
    "\n",
    "\n",
    "    #####################################\n",
    "    #  Open Communication with the QOP  #\n",
    "    #####################################\n",
    "    qmm = QuantumMachinesManager(machine.network.qop_ip, cluster_name=machine.network.cluster_name, octave=octave_config)\n",
    "\n",
    "    simulation = False\n",
    "\n",
    "    qm = qmm.open_qm(config)\n",
    "    job = qm.execute(resonator_spec_2D)\n",
    "    # Get results from QUA program\n",
    "    results = fetching_tool(job, data_list=[\"I\", \"Q\", \"iteration\", \"df\"], mode=\"live\")\n",
    "\n",
    "    fig = plt.figure(1)\n",
    "    plt.rcParams['figure.figsize'] = [12, 8]\n",
    "    interrupt_on_close(fig, job)  #  Interrupts the job when closing the figure\n",
    "\n",
    "    # Progress bar\n",
    "    progress_counter(idx_dc, len(dcs))\n",
    "\n",
    "    while results.is_processing():\n",
    "        I_tmp, Q_tmp, iteration_tmp, df_tmp = results.fetch_all()\n",
    "        I_tmp = u.demod2volts(I_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "        Q_tmp = u.demod2volts(Q_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "\n",
    "        # Live plotting\n",
    "        plt.subplot(211)\n",
    "        plt.cla()\n",
    "        plt.title(\"Resonator spectroscopy amplitude\")\n",
    "        plt.plot((dfs ) / u.MHz, np.sqrt(I_tmp**2 + Q_tmp**2), \".\")\n",
    "        plt.xlabel(\"Frequency [MHz]\")\n",
    "        plt.ylabel(r\"$\\sqrt{I^2 + Q^2}$ [a.u.]\")\n",
    "        plt.subplot(212)\n",
    "        plt.cla()\n",
    "        # detrend removes the linear increase of phase\n",
    "        phase = signal.detrend(np.unwrap(np.angle(I_tmp + 1j * Q_tmp)))\n",
    "        plt.title(\"Resonator spectroscopy phase\")\n",
    "        plt.plot((dfs ) / u.MHz, phase, \".\")\n",
    "        plt.xlabel(\"Frequency [MHz]\")\n",
    "        plt.ylabel(\"Phase [rad]\")\n",
    "        plt.pause(0.1)\n",
    "\n",
    "    if idx_dc == 0:\n",
    "        I_2D = I_tmp\n",
    "        Q_2D = Q_tmp\n",
    "        df_2D = df_tmp\n",
    "    else:\n",
    "        I_2D = np.hstack([I_2D, I_tmp])\n",
    "        Q_2D = np.hstack([Q_2D, Q_tmp])\n",
    "        df_2D = np.hstack([df_2D, df_tmp])\n",
    "\n",
    "# I_2D = np.reshape(I_2D, (len(dcs), len(I_tmp)))\n",
    "# Q_2D = np.reshape(Q_2D, (len(dcs), len(Q_tmp)))\n",
    "# Q_2D = np.reshape(Q_2D, (len(dcs), len(Q_tmp)))\n",
    "# # 2D plot\n",
    "# fig = plt.figure()\n",
    "# plt.rcParams['figure.figsize'] = [12, 8]\n",
    "# # 2D spectroscopy plot\n",
    "# plt.subplot(211)\n",
    "# plt.cla()\n",
    "# plt.title(\"Resonator spectroscopy tuning curve\")\n",
    "# plt.pcolor(dfs/ u.MHz, dcs, np.sqrt(I_2D**2 + Q_2D**2),cmap=\"seismic\")\n",
    "# plt.xlabel(\"DC flux level [V]\")\n",
    "# plt.ylabel(\"Frequency [MHz]\")\n",
    "# plt.colorbar()\n",
    "# #plt.axvline(x=0)\n",
    "# plt.subplot(212)\n",
    "# plt.cla()\n",
    "# plt.title(\"Resonator spectroscopy phase\")\n",
    "# phase = signal.detrend(np.unwrap(np.angle(I_2D + 1j * Q_2D)))\n",
    "# plt.pcolor(dfs/ u.MHz, dcs, phase ,cmap=\"seismic\")\n",
    "# plt.xlabel(\"DC flux level [V]\")\n",
    "# plt.ylabel(\"Frequency [MHz]\")\n",
    "# plt.colorbar()\n",
    "# #plt.axvline(x=0)\n",
    "# #plt.pause(0.1)\n",
    "# plt.tight_layout()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4914612",
   "metadata": {},
   "outputs": [],
   "source": [
    "sz = int(len(df_2D)/len(dcs))\n",
    "I_2Dr = np.reshape(I_2D, (-1,sz))\n",
    "Q_2Dr = np.reshape(Q_2D, (-1,sz))\n",
    "df_2Dr = np.reshape(df_2D, (-1,sz))\n",
    "df_2Dr\n",
    "arr = np.array([df_2Dr, I_2Dr, Q_2Dr])\n",
    "data = xr.DataArray(arr, dims = (\"vals\", \"flux\", \"freq\"), coords={'flux': dcs})\n",
    "vals.data[2]\n",
    "fig = \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "762e8984",
   "metadata": {},
   "outputs": [],
   "source": [
    "    print(datetime.datetime.now(),6)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "00d2f437",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:29:06.289277 1\n",
      "2023-08-16 22:29:06.415941 2\n",
      "2023-08-16 22:29:07.552953 3\n",
      "2023-08-16 22:29:17,707 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:29:17,844 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:29:17,854 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:29:17.855703 4\n",
      "2023-08-16 22:29:18,548 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:29:18,677 - qm - INFO     - Executing program\n",
      "2023-08-16 22:29:27.495375 3                                 ] 2.7% (n=1/37)\n",
      "2023-08-16 22:29:37,596 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:29:37,695 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:29:37,706 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:29:37.706292 4\n",
      "2023-08-16 22:29:38,207 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:29:38,351 - qm - INFO     - Executing program\n",
      "2023-08-16 22:29:47.175759 3                                 ] 5.4% (n=2/37)\n",
      "2023-08-16 22:29:57,269 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:29:57,362 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:29:57,375 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:29:57.376572 4\n",
      "2023-08-16 22:29:57,873 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:29:57,980 - qm - INFO     - Executing program\n",
      "2023-08-16 22:30:06.852780 3                                 ] 8.1% (n=3/37)\n",
      "2023-08-16 22:30:16,963 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:30:17,069 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:30:17,082 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:30:17.084858 4\n",
      "2023-08-16 22:30:17,864 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:30:18,023 - qm - INFO     - Executing program\n",
      "2023-08-16 22:30:26.829495 3                                 ] 10.8% (n=4/37)\n",
      "2023-08-16 22:30:36,946 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:30:37,061 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:30:37,074 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:30:37.075460 4\n",
      "2023-08-16 22:30:37,593 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:30:37,740 - qm - INFO     - Executing program\n",
      "2023-08-16 22:30:46.593622 3                                 ] 13.5% (n=5/37)\n",
      "2023-08-16 22:30:56,715 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:30:56,792 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:30:56,802 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:30:56.803651 4\n",
      "2023-08-16 22:30:57,489 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:30:57,607 - qm - INFO     - Executing program\n",
      "2023-08-16 22:31:06.428530 3                                 ] 16.2% (n=6/37)\n",
      "2023-08-16 22:31:16,546 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:31:16,637 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:31:16,651 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:31:16.652933 4\n",
      "2023-08-16 22:31:17,132 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:31:17,280 - qm - INFO     - Executing program\n",
      "2023-08-16 22:31:26.093978 3                                 ] 18.9% (n=7/37)\n",
      "2023-08-16 22:31:36,210 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:31:36,317 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:31:36,330 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:31:36.331523 4\n",
      "2023-08-16 22:31:37,168 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:31:37,328 - qm - INFO     - Executing program\n",
      "2023-08-16 22:31:46.186683 3                                 ] 21.6% (n=8/37)\n",
      "2023-08-16 22:31:56,291 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:31:56,373 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:31:56,387 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:31:56.389139 4\n",
      "2023-08-16 22:31:56,877 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:31:57,015 - qm - INFO     - Executing program\n",
      "2023-08-16 22:32:05.816202 3                                 ] 24.3% (n=9/37)\n",
      "2023-08-16 22:32:15,957 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:32:16,052 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:32:16,065 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:32:16.067673 4\n",
      "2023-08-16 22:32:16,798 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:32:16,931 - qm - INFO     - Executing program\n",
      "2023-08-16 22:32:25.708931 3                                 ] 27.0% (n=10/37)\n",
      "2023-08-16 22:32:35,834 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:32:35,940 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:32:35,954 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:32:35.955300 4\n",
      "2023-08-16 22:32:36,443 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:32:36,582 - qm - INFO     - Executing program\n",
      "2023-08-16 22:32:45.401413 3                                 ] 29.7% (n=11/37)\n",
      "2023-08-16 22:32:55,521 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:32:55,656 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:32:55,670 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:32:55.671469 4\n",
      "2023-08-16 22:32:56,431 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:32:56,564 - qm - INFO     - Executing program\n",
      "2023-08-16 22:33:05.339413 3                                 ] 32.4% (n=12/37)\n",
      "2023-08-16 22:33:15,438 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:33:15,541 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:33:15,554 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:33:15.556289 4\n",
      "2023-08-16 22:33:16,101 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:33:16,231 - qm - INFO     - Executing program\n",
      "2023-08-16 22:33:25.040603 3                                 ] 35.1% (n=13/37)\n",
      "2023-08-16 22:33:35,149 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:33:35,267 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:33:35,280 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:33:35.281774 4\n",
      "2023-08-16 22:33:36,059 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:33:36,208 - qm - INFO     - Executing program\n",
      "2023-08-16 22:33:45.095290 3#                                ] 37.8% (n=14/37)\n",
      "2023-08-16 22:33:55,208 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:33:55,317 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:33:55,330 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:33:55.331033 4\n",
      "2023-08-16 22:33:55,841 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:33:56,006 - qm - INFO     - Executing program\n",
      "2023-08-16 22:34:04.836242 3###                              ] 40.5% (n=15/37)\n",
      "2023-08-16 22:34:14,952 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:34:15,083 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:34:15,097 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:34:15.099643 4\n",
      "2023-08-16 22:34:15,789 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:34:15,934 - qm - INFO     - Executing program\n",
      "2023-08-16 22:34:24.717528 3####                             ] 43.2% (n=16/37)\n",
      "2023-08-16 22:34:34,851 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:34:35,004 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:34:35,013 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:34:35.015487 4\n",
      "2023-08-16 22:34:35,542 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:34:35,706 - qm - INFO     - Executing program\n",
      "2023-08-16 22:34:44.490406 3#####                            ] 45.9% (n=17/37)\n",
      "2023-08-16 22:34:54,598 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:34:54,761 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:34:54,776 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:34:54.777347 4\n",
      "2023-08-16 22:34:55,507 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:34:55,682 - qm - INFO     - Executing program\n",
      "2023-08-16 22:35:04.441779 3#######                          ] 48.6% (n=18/37)\n",
      "2023-08-16 22:35:14,574 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:35:14,704 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:35:14,718 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:35:14.720249 4\n",
      "2023-08-16 22:35:15,230 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:35:15,362 - qm - INFO     - Executing program\n",
      "2023-08-16 22:35:24.175533 3########                         ] 51.4% (n=19/37)\n",
      "2023-08-16 22:35:34,314 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:35:34,445 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:35:34,460 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:35:34.461602 4\n",
      "2023-08-16 22:35:35,196 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:35:35,358 - qm - INFO     - Executing program\n",
      "2023-08-16 22:35:44.190021 3##########                       ] 54.1% (n=20/37)\n",
      "2023-08-16 22:35:54,290 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:35:54,367 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:35:54,381 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:35:54.382561 4\n",
      "2023-08-16 22:35:54,840 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:35:54,985 - qm - INFO     - Executing program\n",
      "2023-08-16 22:36:03.814123 3###########                      ] 56.8% (n=21/37)\n",
      "2023-08-16 22:36:13,914 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:36:14,002 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:36:14,034 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:36:14.035294 4\n",
      "2023-08-16 22:36:14,819 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:36:14,956 - qm - INFO     - Executing program\n",
      "2023-08-16 22:36:23.754784 3############                     ] 59.5% (n=22/37)\n",
      "2023-08-16 22:36:33,865 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:36:33,990 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:36:34,001 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:36:34.002700 4\n",
      "2023-08-16 22:36:34,512 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:36:34,652 - qm - INFO     - Executing program\n",
      "2023-08-16 22:36:43.393755 3##############                   ] 62.2% (n=23/37)\n",
      "2023-08-16 22:36:53,502 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:36:53,617 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:36:53,631 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:36:53.632062 4\n",
      "2023-08-16 22:36:54,444 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:36:54,585 - qm - INFO     - Executing program\n",
      "2023-08-16 22:37:03.390442 3###############                  ] 64.9% (n=24/37)\n",
      "2023-08-16 22:37:13,484 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:37:13,587 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:37:13,611 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:37:13.612540 4\n",
      "2023-08-16 22:37:14,115 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:37:14,214 - qm - INFO     - Executing program\n",
      "2023-08-16 22:37:23.045315 3################                 ] 67.6% (n=25/37)\n",
      "2023-08-16 22:37:33,164 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:37:33,282 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:37:33,297 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:37:33.298896 4\n",
      "2023-08-16 22:37:34,100 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:37:34,236 - qm - INFO     - Executing program\n",
      "2023-08-16 22:37:43.118635 3##################               ] 70.3% (n=26/37)\n",
      "2023-08-16 22:37:53,217 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:37:53,300 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:37:53,311 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:37:53.312378 4\n",
      "2023-08-16 22:37:53,735 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:37:53,858 - qm - INFO     - Executing program\n",
      "2023-08-16 22:38:02.665543 3###################              ] 73.0% (n=27/37)\n",
      "2023-08-16 22:38:12,782 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:38:12,903 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:38:12,914 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:38:12.915987 4\n",
      "2023-08-16 22:38:13,726 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:38:13,856 - qm - INFO     - Executing program\n",
      "2023-08-16 22:38:22.617095 3####################             ] 75.7% (n=28/37)\n",
      "2023-08-16 22:38:32,747 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:38:32,861 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:38:32,873 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:38:32.874666 4\n",
      "2023-08-16 22:38:33,369 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:38:33,517 - qm - INFO     - Executing program\n",
      "2023-08-16 22:38:42.318412 3######################           ] 78.4% (n=29/37)\n",
      "2023-08-16 22:38:52,423 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:38:52,522 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:38:52,536 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:38:52.538671 4\n",
      "2023-08-16 22:38:53,413 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:38:53,520 - qm - INFO     - Executing program\n",
      "2023-08-16 22:39:02.326564 3#######################          ] 81.1% (n=30/37)\n",
      "2023-08-16 22:39:12,419 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:39:12,545 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:39:12,557 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:39:12.558207 4\n",
      "2023-08-16 22:39:13,073 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:39:13,217 - qm - INFO     - Executing program\n",
      "2023-08-16 22:39:22.035865 3########################         ] 83.8% (n=31/37)\n",
      "2023-08-16 22:39:32,142 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:39:32,240 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:39:32,252 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:39:32.254539 4\n",
      "2023-08-16 22:39:33,034 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:39:33,136 - qm - INFO     - Executing program\n",
      "2023-08-16 22:39:41.987509 3##########################       ] 86.5% (n=32/37)\n",
      "2023-08-16 22:39:52,089 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:39:52,179 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:39:52,189 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:39:52.190225 4\n",
      "2023-08-16 22:39:52,631 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:39:52,861 - qm - INFO     - Executing program\n",
      "2023-08-16 22:40:01.683986 3###########################      ] 89.2% (n=33/37)\n",
      "2023-08-16 22:40:11,829 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:40:11,953 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:40:11,963 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:40:11.964496 4\n",
      "2023-08-16 22:40:12,667 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:40:12,805 - qm - INFO     - Executing program\n",
      "2023-08-16 22:40:21.612696 3############################     ] 91.9% (n=34/37)\n",
      "2023-08-16 22:40:31,714 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:40:31,811 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:40:31,824 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:40:31.825442 4\n",
      "2023-08-16 22:40:32,313 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:40:32,420 - qm - INFO     - Executing program\n",
      "2023-08-16 22:40:41.242260 3##############################   ] 94.6% (n=35/37)\n",
      "2023-08-16 22:40:51,339 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-08-16 22:40:51,425 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:40:51,437 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:40:51.438995 4\n",
      "2023-08-16 22:40:52,295 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:40:52,423 - qm - INFO     - Executing program\n",
      "2023-08-16 22:41:01.210113 3###############################  ] 97.3% (n=36/37)\n",
      "2023-08-16 22:41:11,323 - qm - ERROR    - Encountered connection error from QOP\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\base_api.py\", line 27, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\api\\frontend_api.py\", line 79, in get_version\n",
      "    response = run_async(self._stub.get_version(Empty(), timeout=self._timeout))\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\utils\\async_utils.py\", line 37, in run_async\n",
      "    return create_future(coroutine).result()  # type: ignore[no-any-return]\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 444, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\painter\\.conda\\envs\\labber-qm-env\\lib\\concurrent\\futures\\_base.py\", line 389, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\qm\\grpc\\frontend\\__init__.py\", line 697, in get_version\n",
      "    return await self._unary_unary(\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\betterproto\\grpc\\grpclib_client.py\", line 85, in _unary_unary\n",
      "    response = await stream.recv_message()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 425, in recv_message\n",
      "    await self.recv_initial_metadata()\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 371, in recv_initial_metadata\n",
      "    self._raise_for_status(headers_map)\n",
      "  File \"C:\\Users\\painter\\AppData\\Roaming\\Python\\Python38\\site-packages\\grpclib\\client.py\", line 296, in _raise_for_status\n",
      "    raise GRPCError(grpc_status,\n",
      "grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, \"Received :status = '302'\", None)\n",
      "2023-08-16 22:41:11,439 - qm - INFO     - Performing health check\n",
      "2023-08-16 22:41:11,452 - qm - INFO     - Health check passed\n",
      "2023-08-16 22:41:11.453760 4\n",
      "2023-08-16 22:41:11,928 - qm - INFO     - Sending program to QOP for compilation\n",
      "2023-08-16 22:41:12,069 - qm - INFO     - Executing program\n",
      "Progress: [##################################################] 100.0% (n=37/37)\n",
      "2023-08-16 22:41:19.881224 5\n",
      "2023-08-16 22:41:19.881224 6\n",
      "2023-08-17 07:08:08,586 - qm - ERROR    - Octave \"octave1\" lost monitor connection\n",
      "2023-08-17 07:08:51,053 - qm - INFO     - Octave \"octave1\" restored monitor connection\n"
     ]
    }
   ],
   "source": [
    "from qm.qua import *\n",
    "from qm.QuantumMachinesManager import QuantumMachinesManager\n",
    "from qm import SimulationConfig, LoopbackInterface\n",
    "from configuration import *\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from scipy import signal\n",
    "from qualang_tools.loops import from_array\n",
    "import qdac\n",
    "import random\n",
    "import math\n",
    "import time\n",
    "%matplotlib qt\n",
    "\n",
    "# Start to save data\n",
    "import datetime \n",
    "import os\n",
    "import pandas as pd \n",
    "\n",
    "now = datetime.datetime.now()\n",
    "year = now.strftime(\"%Y\")\n",
    "month = now.strftime(\"%m\")\n",
    "day = now.strftime(\"%d\")\n",
    "hour = now.strftime(\"%H\")\n",
    "minute = now.strftime(\"%M\")\n",
    "second  = now.strftime(\"%S\")\n",
    "\n",
    "tPath = os.path.join(r'Z:\\LabberData_DF5\\QM_Data_DF5',year,month,'Data_'+month+day)\n",
    "if not os.path.exists(tPath):\n",
    "   os.makedirs(tPath)\n",
    "exp_name = 'RR_spec_wFlux'\n",
    "qubit_name = 'Q2'\n",
    "\n",
    "f_str =exp_name + '_'+ qubit_name +'_'+ hour+ '_' + minute +'_' + second\n",
    "f_name= f_str+'.csv'\n",
    "j_name = f_str + '_state.json'\n",
    "p_name= f_str+'.png'\n",
    "\n",
    "# End to save data\n",
    "\n",
    "print(datetime.datetime.now(),1)\n",
    "#########################################\n",
    "# Set-up the machine and get the config #\n",
    "#########################################\n",
    "machine = QuAM(\"quam_state.json\")\n",
    "#machine.resonators[0].f_readout+=1.68e6\n",
    "# machine.resonators[0].readout_pulse_amp=0.27\n",
    "config = build_config(machine)\n",
    "print(datetime.datetime.now(),2)\n",
    "##############################\n",
    "# Program-specific variables #\n",
    "##############################\n",
    "\n",
    "n_avg = 1000  # Number of averaging loops\n",
    "\n",
    "cooldown_time = 50  # Resonator cooldown time \n",
    "flux_settle_time = 250  # Flux settle time \n",
    "\n",
    "flux_pts = 250\n",
    "\n",
    "#dcs = np.linspace(-0.49, 0.49, flux_pts)\n",
    "dcs = np.arange(-9,9.5,0.5)\n",
    "dfs = np.arange(-14.62e6, 15.40e6, 0.2e6)\n",
    "\n",
    "number_of_qubits = 1\n",
    "resonators_list = [i for i in range(number_of_qubits)]\n",
    "res_if_list = [machine.resonators[i].f_readout - machine.resonators[i].lo for i in range(number_of_qubits)]\n",
    "\n",
    "qubit_index = 0\n",
    "\n",
    "with qdac.qdac('COM3') as q:\n",
    "    for idx_dc, _ in enumerate(dcs):\n",
    "        dc = dcs[idx_dc]\n",
    "        q.setDCVoltage(channel=6, volts=dc)\n",
    "\n",
    "    ###################\n",
    "    # The QUA program #\n",
    "    ###################\n",
    "        time.sleep(1)\n",
    "        \n",
    "        with program() as resonator_spec_2D:\n",
    "            n = declare(int)  # Averaging index\n",
    "            df = declare(int)  # Resonator frequency\n",
    "            # dc = declare(fixed)  # flux dc level|\n",
    "            I = declare(fixed)\n",
    "            Q = declare(fixed)\n",
    "            I_st = declare_stream()\n",
    "            Q_st = declare_stream()\n",
    "            n_st = declare_stream()\n",
    "            #wait(flux_settle_time , machine.resonators[qubit_index].name, machine.qubits[qubit_index].name)\n",
    "            \n",
    "            with for_(n, 0, n < n_avg, n + 1):\n",
    "                with for_(*from_array(df, dfs)):\n",
    "                    # Update the resonator frequency\n",
    "                    update_frequency(machine.resonators[qubit_index].name, df + res_if_list[qubit_index])\n",
    "                    # with for_(*from_array(dc, dcs)):\n",
    "                        # Flux sweeping\n",
    "                        # set_dc_offset(machine.flux_lines[qubit_index].name, \"single\", dc)\n",
    "                        # wait(flux_settle_time * u.ns, machine.resonators[qubit_index].name, machine.qubits[qubit_index].name)\n",
    "                        # Measure the resonator\n",
    "                    measure(\n",
    "                        \"readout\",\n",
    "                        machine.resonators[qubit_index].name,\n",
    "                        None,\n",
    "                        dual_demod.full(\"cos\", \"out1\", \"sin\", \"out2\", I),\n",
    "                        dual_demod.full(\"minus_sin\", \"out1\", \"cos\", \"out2\", Q),\n",
    "                    )\n",
    "                    # Wait for the resonator to cooldown\n",
    "                    wait(cooldown_time * u.us - machine.resonators[0].readout_pulse_length * u.ns - 240 * u.ns, machine.resonators[qubit_index].name)\n",
    "                    # Save data to the stream processing\n",
    "                    save(I, I_st)\n",
    "                    save(Q, Q_st)\n",
    "                save(n, n_st)\n",
    "        \n",
    "            with stream_processing():\n",
    "                # I_st.buffer(len(dcs)).buffer(len(dfs)).average().save(\"I\")\n",
    "                # Q_st.buffer(len(dcs)).buffer(len(dfs)).average().save(\"Q\")\n",
    "                I_st.buffer(len(dfs)).average().save(\"I\")\n",
    "                Q_st.buffer(len(dfs)).average().save(\"Q\")\n",
    "                n_st.save(\"iteration\")\n",
    "\n",
    "\n",
    "        #####################################\n",
    "        #  Open Communication with the QOP  #\n",
    "        #####################################\n",
    "        print(datetime.datetime.now(),3)\n",
    "        qmm = QuantumMachinesManager(machine.network.qop_ip, cluster_name=machine.network.cluster_name, octave=octave_config)\n",
    "        print(datetime.datetime.now(),4)\n",
    "        simulation = False\n",
    "        \n",
    "        qm = qmm.open_qm(config)\n",
    "        job = qm.execute(resonator_spec_2D)\n",
    "        # Get results from QUA program\n",
    "        results = fetching_tool(job, data_list=[\"I\", \"Q\", \"iteration\"], mode=\"live\")\n",
    "\n",
    "#         fig = plt.figure(1)\n",
    "#         plt.rcParams['figure.figsize'] = [12, 8]\n",
    "#         interrupt_on_close(fig, job)  #  Interrupts the job when closing the figure\n",
    "\n",
    "        # Progress bar\n",
    "        progress_counter(idx_dc, len(dcs))\n",
    "            \n",
    "        while results.is_processing():\n",
    "            I_tmp, Q_tmp, iteration_tmp = results.fetch_all()\n",
    "            I_tmp = u.demod2volts(I_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "            Q_tmp = u.demod2volts(Q_tmp, machine.resonators[qubit_index].readout_pulse_length)\n",
    "\n",
    "    \n",
    "#             # Live plotting\n",
    "#             plt.subplot(211)\n",
    "#             plt.cla()\n",
    "#             plt.title(\"Resonator spectroscopy amplitude\")\n",
    "#             plt.plot((dfs ) / u.MHz, np.sqrt(I_tmp**2 + Q_tmp**2), \".\")\n",
    "#             plt.xlabel(\"Frequency [MHz]\")\n",
    "#             plt.ylabel(r\"$\\sqrt{I^2 + Q^2}$ [a.u.]\")\n",
    "#             plt.subplot(212)\n",
    "#             plt.cla()\n",
    "#             # detrend removes the linear increase of phase\n",
    "#             phase = signal.detrend(np.unwrap(np.angle(I_tmp + 1j * Q_tmp)))\n",
    "#             plt.title(\"Resonator spectroscopy phase\")\n",
    "#             plt.plot((dfs ) / u.MHz, phase, \".\")\n",
    "#             plt.xlabel(\"Frequency [MHz]\")\n",
    "#             plt.ylabel(\"Phase [rad]\")\n",
    "#             plt.pause(0.1)\n",
    "            \n",
    "        if idx_dc == 0:\n",
    "            I_2D = I_tmp\n",
    "            Q_2D = Q_tmp\n",
    "        else:\n",
    "            I_2D = np.hstack([I_2D, I_tmp])\n",
    "            Q_2D = np.hstack([Q_2D, Q_tmp])\n",
    "print(datetime.datetime.now(),5)\n",
    "I_2D = np.reshape(I_2D, (len(dcs), len(I_tmp)))\n",
    "Q_2D = np.reshape(Q_2D, (len(dcs), len(Q_tmp)))\n",
    "print(datetime.datetime.now(),6)\n",
    "# # 2D plot\n",
    "# fig = plt.figure()\n",
    "# plt.rcParams['figure.figsize'] = [12, 8]\n",
    "# # 2D spectroscopy plot\n",
    "# plt.subplot(211)\n",
    "# plt.cla()\n",
    "# plt.title(\"Resonator spectroscopy tuning curve\")\n",
    "# plt.pcolor(dfs/ u.MHz, dcs, np.sqrt(I_2D**2 + Q_2D**2),cmap=\"seismic\")\n",
    "# plt.xlabel(\"DC flux level [V]\")\n",
    "# plt.ylabel(\"Frequency [MHz]\")\n",
    "# plt.colorbar()\n",
    "# #plt.axvline(x=0)\n",
    "# plt.subplot(212)\n",
    "# plt.cla()\n",
    "# plt.title(\"Resonator spectroscopy phase\")\n",
    "# phase = signal.detrend(np.unwrap(np.angle(I_2D + 1j * Q_2D)))\n",
    "# plt.pcolor(dfs/ u.MHz, dcs, phase ,cmap=\"seismic\")\n",
    "# plt.xlabel(\"DC flux level [V]\")\n",
    "# plt.ylabel(\"Frequency [MHz]\")\n",
    "# plt.colorbar()\n",
    "# #plt.axvline(x=0)\n",
    "# #plt.pause(0.1)\n",
    "# plt.tight_layout()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ec4dc24d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "test\n"
     ]
    }
   ],
   "source": [
    "print(\"test\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23744037",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
